import { Router } from 'express';
import AuthRouter from './admin/AuthRouter';
import UserRouter from './admin/UserRouter';
import SedeRouter from './admin/SedeRouter';
import RolRouter from './admin/RolRouter';
import PermisoRouter from './admin/PermisoRouter';
import VoluntarioRouter from './admin/VoluntarioRouter';
import CuerpoFilialRouter from './admin/CuerpoFilialRouter';
import EstadoRouter from './admin/EstadoRouter';
import DepartamentoXMunicipioRouter from './admin/DepartamentoXMunicipioRouter';
import ModalidadRouter from './admin/ModalidadRouter';
import TipoVoluntarioRouter from './admin/TipoVoluntarioRouter';
import TipoSedeRouter from './admin/TipoSedeRouter';
import TipoEmergenciaRouter from './admin/TipoEmergenciaRouter';
import EmergenciaRouter from './admin/EmergenciaRouter';
import HospitalRouter from './admin/HospitalRouter';
import VehiculoRouter from './admin/VehiculoRouter';
import SeccionalRouter from './admin/SeccionalRouter';
import { checkJWT } from '../../middlewares/checkJWT';
import { checkRole } from '../../middlewares/checkRole';
import EmergenciaAsignadaRouter from './admin/EmergenciaAsignadaRouter';
import EmergenciaRealizadaRouter from './admin/EmergenciaRealizadaRouter';
import PacienteRouter from './admin/PacienteRouter';

const router: Router = Router();

router.use('/auth', AuthRouter);
router.use('/usuario', [checkJWT, checkRole], UserRouter);
router.use('/sede', [checkJWT, checkRole], SedeRouter);
router.use('/rol', [checkJWT, checkRole], RolRouter);
router.use('/permiso', [checkJWT, checkRole], PermisoRouter);
router.use('/voluntario', [checkJWT, checkRole], VoluntarioRouter);
router.use('/paciente', [checkJWT, checkRole], PacienteRouter);
router.use('/cuerpoFilial', [checkJWT, checkRole], CuerpoFilialRouter);
router.use('/estado', [checkJWT, checkRole], EstadoRouter);
router.use('/modalidad', [checkJWT, checkRole], ModalidadRouter);
router.use('/emergencia', /*[checkJWT, checkRole],*/ EmergenciaRouter);
router.use('/emergenciaAsignada', /*[checkJWT, checkRole],*/ EmergenciaAsignadaRouter);
router.use('/emergenciaRealizada', /*[checkJWT, checkRole],*/ EmergenciaRealizadaRouter);
router.use('/vehiculo', /*[checkJWT, checkRole],*/ VehiculoRouter);
router.use('/hospital', /*[checkJWT, checkRole],*/ HospitalRouter);
router.use('/seccional', /*[checkJWT, checkRole],*/SeccionalRouter);
router.use('/departamentoXMunicipio',/* [checkJWT, checkRole],*/ DepartamentoXMunicipioRouter);
router.use('/tipoSede', [checkJWT, checkRole], TipoSedeRouter);
router.use('/tipoVoluntario', [checkJWT, checkRole], TipoVoluntarioRouter);
router.use('/tipoEmergencia', /*[checkJWT, checkRole],*/ TipoEmergenciaRouter);

export default router;
